### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by Kibele** [ethanhann/sb-admin-2#2]
Hi,
This is my first trying and I'm new to gulp. I got this:

kibele@ubuntu:/var/www/html/sb-admin-2$ gulp
[15:59:54] Using gulpfile /var/www/html/sb-admin-2/gulpfile.js
[15:59:54] Starting 'jshint'...
[15:59:54] Starting 'bower'...
[15:59:55] Finished 'jshint' after 485 ms
[15:59:58] Finished 'bower' after 3.85 s
[15:59:58] Starting 'copy'...
[15:59:58] 'copy' app.html 20 B

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (/var/www/html/sb-admin-2/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/var/www/html/sb-admin-2/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at Stream.endStream (/var/www/html/sb-admin-2/node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
    at _end (/var/www/html/sb-admin-2/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
    at Stream.stream.end (/var/www/html/sb-admin-2/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/var/www/html/sb-admin-2/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:117:20)

Sincerely...

**Comment by ethanhann** [comment]
I don't think this error is related to the code in this repository as I cannot reproduce it. You could try deleting the **node_modules** directory, run **npm install**, and then run **gulp** again.

**Comment by Kibele** [comment]
I've tried many times, but it does not work. On two different Ubuntu 14.04 box...

I cleaned cache, used different nodejs installations, different versions... But in all cases, there occurs the same error: "Unhandled stream error in pipe."

gandalf@boost:~/Projects/sb-admin-2$ gulp
[12:02:38] Using gulpfile ~/Projects/sb-admin-2/gulpfile.js
[12:02:38] Starting 'jshint'...
[12:02:38] Starting 'bower'...
[12:02:38] Finished 'bower' after 348 ms
[12:02:38] Starting 'copy'...
[12:02:39] Finished 'jshint' after 557 ms
[12:02:39] gulp-size: 'copy' app.html 20 B
WARN: Couldn't figure out mapping for ?:2,0 → 1,32119 []
WARN: Couldn't figure out mapping for ?:3,0 → 2,32071 []
WARN: Couldn't figure out mapping for ?:7,0 → 6,32057 []
WARN: Couldn't figure out mapping for ?:11,0 → 10,32080 []
WARN: Couldn't figure out mapping for ?:13,0 → 12,32083 []
WARN: Couldn't figure out mapping for ?:15,0 → 14,32028 []
WARN: Couldn't figure out mapping for ?:16,0 → 15,32059 []
WARN: Couldn't figure out mapping for ?:18,0 → 17,32026 []
WARN: Couldn't figure out mapping for ?:23,0 → 22,32208 []
WARN: Couldn't figure out mapping for ?:24,0 → 23,32014 []
WARN: Couldn't figure out mapping for ?:29,0 → 28,32051 []
WARN: Couldn't figure out mapping for ?:32,0 → 31,32472 []
WARN: Couldn't figure out mapping for ?:33,0 → 32,32053 []
WARN: Couldn't figure out mapping for ?:35,0 → 34,32040 []
WARN: Couldn't figure out mapping for ?:36,0 → 35,32031 []
WARN: Couldn't figure out mapping for ?:37,0 → 36,32069 []
WARN: Couldn't figure out mapping for ?:39,0 → 38,32097 []
WARN: Couldn't figure out mapping for ?:40,0 → 39,32012 []
WARN: Couldn't figure out mapping for ?:41,0 → 40,32318 []
WARN: Couldn't figure out mapping for ?:42,0 → 41,32007 []
WARN: Couldn't figure out mapping for ?:44,0 → 43,32062 []
WARN: Couldn't figure out mapping for ?:45,0 → 44,32130 []
WARN: Couldn't figure out mapping for ?:48,0 → 47,32083 []
WARN: Couldn't figure out mapping for ?:49,0 → 48,32090 []
WARN: Couldn't figure out mapping for ?:50,0 → 49,32011 []
WARN: Couldn't figure out mapping for ?:51,0 → 50,32042 []

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (/home/gandalf/Projects/sb-admin-2/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/home/gandalf/Projects/sb-admin-2/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:95:17)
    at Stream.endStream (/home/gandalf/Projects/sb-admin-2/node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
    at _end (/home/gandalf/Projects/sb-admin-2/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/gandalf/Projects/sb-admin-2/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/gandalf/Projects/sb-admin-2/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)

I have just installed Node Version Manager (creationix/nvm). Do you prefer a nodejs/npm version?

**Comment by Kibele** [comment]
"gulp --dev" works fine by the way...

**Comment by Kibele** [comment]
I removed the line: https://github.com/ethanhann/sb-admin-2/blob/master/gulpfile.js#L99

Now, I don't have any errors.

**Comment by ethanhann** [comment]
As of version [0.1.0](https://github.com/ethanhann/sb-admin-2/releases/tag/0.1.0) the gulp setup has been completely replaced with the one provided by [Swiip/generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular). This should resolve your issue.
